### ISSUE TITLE
JOSS Review: `MOFStructures` link is not correct

### ISSUE THREAD

**Issue by arosen93** [nomad-coe/workflow-parsers#21]
In the `README`, the `MOFStructures` link just points back to the same `workflow-parsers` repo. As a MOF researcher using workflow tools, I am also very intrigued about what this may be...

Disclaimer: I'm reviewing the JOSS paper here https://github.com/openjournals/joss-reviews/issues/5388#issuecomment-1558214401

**Comment by lauri-codes** [comment]
Hi @arosen93!

Thanks for pointing this out. MOFStructures was a legacy parser that we used for parsing a custom format from one of our partner universities. This approach has since been dropped in favor of developing a more generic approach that does not require any special formats but instead relies on running a more automated pipeline based on [pyzeo](https://github.com/nomad-coe/pyzeo) and some other tools. The idea is to get at least a semi-automated identification and processing of MOFs from any type of computational entry in NOMAD.

I will remove the legacy code and any references to it to prevent further confusion.

**Comment by Pepe-Marquez** [comment]
Hi @arosen93, this has now been merged. I am closing this issue. 
We will keep posted once the other MOF pipeline is ready! Thanks!
